### ISSUE TITLE
Update  ibc-proto to  ibc-go-V4.0.0

### ISSUE THREAD

**Issue by Wizdave97** [ComposableFi/ibc-rs#49]
## Update Ibc proto files to match ibc-go-V4.0.0

Some `ibc-core` struct definitions  have changed in the latest ibc-go-v4.0.0, this affects client, connections, channels messages.

We should update our `ibc-proto` files to reflect these changes and in turn update `ibc-rs::core` to reflect these changes.

Not a pressing issue for now, just putting it here so it could be done before we begin parachain to cosmos tests.

**Comment by seunlanlege** [comment]
closed in #58
